import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import SessionWrapper from "~/components/session-wrapper";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionWrapper>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          {children}
          <Toaster position="top-right" />
        </body>
      </html>
    </SessionWrapper>
  );
}
